ci(prettier.yml): use my own commands
and handle prettier exit codes

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -6,18 +6,20 @@ on:
       - main
 
 jobs:
-  prettier:
+  build:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-        with:
-          ref: ${{ github.head_ref }}
-          fetch-depth: 0
 
-      - name: Prettify code
-        uses: creyD/prettier_action@v4.3
-        with:
-          prettier_options: --write **/*.{js,jsx,ts,tsx,tailwind.config.cjs,json,html,md}
-          same_commit: true
+      - name: Check formatting
+        run: |
+          npm run format:check
+          exit_code=$?
+          echo "::set-env name=EXIT_CODE::$exit_code" # Armazena o Exit Code em uma variável de ambiente
+
+      - name: Format if isn't already
+        if: ${{ env.EXIT_CODE == 1 }} # Prettier: 1 Something wasn’t formatted properly
+        run: npm run format
+
